Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm-trance"
    vb.memory = 3072
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
    set -eux

    sudo apt-get update -y
    sudo apt-get install -y make docker.io docker-compose nodejs npm zsh curl git

    sudo -u vagrant -H sh -c '
      export RUNZSH=no
      export CHSH=no
      export KEEP_ZSHRC=yes
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    '

    sudo chsh -s $(which zsh) vagrant

    sudo usermod -aG docker vagrant
  SHELL

end
